### ISSUE TITLE
Virginia aerials overlay broken

### ISSUE THREAD

**Issue by russblau** [Glodenox/wme-om#98]
The Virginia aerial overlay is no longer working in WME OpenMaps.  Virginia recently changed its GIS website from gismaps.vita.virginia.gov to gismaps.vdem.virginia.gov, but just changing the URL in the script doesn't solve the problem.

**Comment by Glodenox** [comment]
This map service now seems to be located at https://gismaps.vdem.virginia.gov/arcgis/services/VBMP_Imagery/MostRecentImagery_WGS/MapServer/WMSServer?request=GetCapabilities&service=WMS. I'll make the necessary changes for it to work again :)

**Comment by russblau** [comment]
Still not working; now getting these errors in the console:

WME Open Maps: Failed to parse response
userscript.html?name=WME%20OpenMaps.user.js&id=cd1baa8c-cb21-41af-8c39-ae85cdcee39d:2074 

WME Open Maps: Function
finalUrl: "http://gismaps.vita.virginia.gov/arcgis/services/MostRecentImagery/MostRecentImagery_WGS/MapServer/WMSServer?LAYERS=0&TRANSPARENT=FALSE&FORMAT=image%2Fjpeg&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A3857&BBOX=-8946495.5373648,4456278.7484055,-8946189.7892517,4456584.4965186&WIDTH=512&HEIGHT=512"readyState: 4responseHeaders: "access-control-allow-origin: *
↵cache-control: private
↵content-length: 7175
↵content-type: text/html; charset=utf-8
↵date: Fri, 26 Feb 2021 20:24:53 GMT
↵server: Microsoft-IIS/7.5
↵x-aspnet-version: 2.0.50727
↵x-powered-by: ASP.NET
↵"status: 200statusText: "OK"arguments: (...)caller: (...)response: (...)responseText: (...)responseXML: (...)get response: ƒ ()get responseText: ƒ ()get responseXML: ƒ ()__proto__: ()=>{}
2userscript.html?name=WME%20OpenMaps.user.js&id=cd1baa8c-cb21-41af-8c39-ae85cdcee39d:1503 

Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at manipulateTile (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=WME%2520OpenMaps.user.js&id=cd1baa8c-cb21-41af-8c39-ae85cdcee39d:1503:29)
    at initialize.eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=WME%2520OpenMaps.user.js&id=cd1baa8c-cb21-41af-8c39-ae85cdcee39d:1677:13)
    at initialize.triggerEvent (https://editor-assets.waze.com/production/js/third_party-f5b414a085c5705d8fda.js:1:1643896)
    at initialize.e.onLoadEnd (https://editor-assets.waze.com/production/js/third_party-f5b414a085c5705d8fda.js:1:1715334)
    at initialize.triggerEvent (https://editor-assets.waze.com/production/js/third_party-f5b414a085c5705d8fda.js:1:1643896)
    at initialize.onImageLoad (https://editor-assets.waze.com/production/js/third_party-f5b414a085c5705d8fda.js:1:1704772)
    at initialize.onImageError (https://editor-assets.waze.com/production/js/third_party-f5b414a085c5705d8fda.js:1:1705215)
    at HTMLImageElement.<anonymous> (https://editor-assets.waze.com/production/js/third_party-f5b414a085c5705d8fda.js:1:1615903)

**Comment by Glodenox** [comment]
It seems to me you are not using the latest version of the script then. It should be version 3.1.16. The URL displayed in the message doesn't exist any more in the script.
